# cronframe.toml example file

# [webserver]
# port = 8098
# ip = "127.0.0.1"

# [logger]
# enabled = true
# dir = "log"
# file_size = 1 # this is in MB
# archive_files = 3 
# latest_file_name = "latest"
# archive_file_name = "archive"
# msg_pattern = "{d(%Y-%m-%d %H:%M:%S %Z)} {l} {t} - {m}{n}"
# level_filter = "info"

# [scheduler]
# job_filter = "None"
# grace = 250 # this is in ms