[package]
name = "cronrs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
cron = "0.12.1"
cronframe = { path = "../cronframe" }
inventory = "0.3.15"
linkme = "0.3.26"
crossbeam-channel = "0.5.12"
once_cell = "1.19.0"